const number1 = 3;
const number2 = 2;
const product = number1 * number2;
console.log('Value of Product: ' + product);
console.log('Type of Product: ' + typeof product);
const charge = 100;
const payment = 90;
const amountRemaining = charge - payment;
console.log('Value of amountRemaining: ' + amountRemaining);
console.log('Type of amountRemaining: ' + typeof amountRemaining);
const tests = 100;
const assignments = 90;
const final = 80;
const grade = (tests + assignments + final) / 3;
console.log('Value of grade: ' + grade);
console.log('Type of grade: ' + typeof grade);
const firstName = 'Ricardo';
const lastName = 'Davila';
const fullName = firstName + ' ' + lastName;
console.log('Value of fullName: ' + fullName);
console.log('Type of fullName: ' + typeof fullName);
const ph = 8;
const isAcidic = ph < 7;
console.log('Value of isAcidic: ' + isAcidic);
console.log('Type of isAcidic: ' + typeof isAcidic);
const numberOfSoldiers = 250;
const isSparta = numberOfSoldiers === 300;
console.log('Value of isSparta: ' + isSparta);
console.log('Type of isSparta: ' + typeof isSparta);
const nickname = fullName + ' is the GOAT';
console.log('Value of nickname: ' + nickname);
console.log('Type of nickname: ' + typeof nickname);
